version: '3'

services: 
    db: 
        image: mongo
        container_name: 'chat-room-db'
        restart: always
        # env_file: 
        #     - ./db.env
        volumes: 
            - ./db:/data/db
    
    #backend:
    #frontend: