version: '3'

services: 
    db: 
        image: mongo
        container_name: 'chat-room-db'
        restart: always
        ports: 
            - "27017:27017"
        volumes: 
            - ./db:/data/db
            - ./config.js:/data/config.js
        command: [--auth]
    
    #backend:
    #frontend: